/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelroombooking;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zheng
 */
public class Update extends javax.swing.JFrame {

    private String inDate;
    private String outDate;
    /**
     * Creates new form RoomBooking
     */
    public Update() {
        initComponents();
        setLocationRelativeTo(null);
        
        Calendar calendar = Calendar.getInstance();
        int day = calendar.get(Calendar.DAY_OF_MONTH);
        int month= calendar.get(Calendar.MONTH);
        int year=calendar.get(Calendar.YEAR);
        
        
        
        
    }
    public String getInDate()
    {
        int inDay = Integer.parseInt(cmbInDay.getSelectedItem().toString());
        int inMonth = Integer.parseInt(cmbInMonth.getSelectedItem().toString());
        int inYear = Integer.parseInt(cmbInYear.getSelectedItem().toString());
        String inDate = inDay+"-" +inMonth+"-"+inYear;
        return inDate;
    }
    public String getOutDate()
    {
        int outDay = Integer.parseInt(cmbOutDay.getSelectedItem().toString());
        int outMonth = Integer.parseInt(cmbOutMonth.getSelectedItem().toString());
        int outYear = Integer.parseInt(cmbOutYear.getSelectedItem().toString());
        String outDate = outDay+"-" +outMonth+"-"+outYear;
        return outDate;
    }
    public long getNumDays(){
        String inDate = getInDate();
        String outDate = getOutDate();
        int total=0;
        long daysDiff=0;
        try {
        // Convert `String` to `Date`
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
            Date dateBefore = sdf.parse(inDate);
            Date dateAfter = sdf.parse(outDate);
            
            if(dateAfter.before(dateBefore)|| dateAfter.equals(dateBefore)){
                JOptionPane.showMessageDialog(null, "Invalid check in date","Error",JOptionPane.ERROR_MESSAGE);
            }else{ 

            // Calculate the number of days between dates
                long timeDiff = Math.abs(dateAfter.getTime() - dateBefore.getTime());
                daysDiff = TimeUnit.DAYS.convert(timeDiff, TimeUnit.MILLISECONDS);
                return daysDiff;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return daysDiff;
    }
    public int getTotal(){
        int total=0;
        long daysDiff = getNumDays();
        total = (int) (daysDiff*350*110/100+10*daysDiff);
        return total;
    }
    
    public static int[] splitDate(String dateString) {
        String[] dateParts = dateString.split("-");
        int[] dateIntArray = new int[3];
        for (int i = 0; i < dateParts.length; i++) {
            dateIntArray[i] = Integer.parseInt(dateParts[i]);
        }
    return dateIntArray;
    }
    
  
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtIcNo = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbOutDay = new javax.swing.JComboBox<>();
        cmbOutMonth = new javax.swing.JComboBox<>();
        cmbOutYear = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbInDay = new javax.swing.JComboBox<>();
        cmbInMonth = new javax.swing.JComboBox<>();
        cmbInYear = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbRoom = new javax.swing.JComboBox<>();
        btnSearchRoom = new javax.swing.JButton();
        txtAmount = new javax.swing.JTextField();
        btnCal = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(236, 242, 247));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 242, 247));
        jLabel4.setText("Conatact Number:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));
        getContentPane().add(txtIcNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 158, -1));
        getContentPane().add(txtPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 158, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 158, -1));

        jPanel1.setBackground(new java.awt.Color(72, 105, 149));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(197, 230, 239));
        jLabel1.setText("Room Booking");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel8.setBackground(new java.awt.Color(236, 242, 247));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 242, 247));
        jLabel8.setText("Check-out Date:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        cmbOutDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmbOutDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOutDayActionPerformed(evt);
            }
        });
        jPanel1.add(cmbOutDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 50, -1));

        cmbOutMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbOutMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOutMonthActionPerformed(evt);
            }
        });
        jPanel1.add(cmbOutMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 50, -1));

        cmbOutYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026" }));
        cmbOutYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOutYearActionPerformed(evt);
            }
        });
        jPanel1.add(cmbOutYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 70, -1));

        btnUpdate.setBackground(new java.awt.Color(236, 242, 247));
        btnUpdate.setForeground(new java.awt.Color(72, 105, 149));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

        btnReset.setBackground(new java.awt.Color(236, 242, 247));
        btnReset.setForeground(new java.awt.Color(72, 105, 149));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 102, -1));

        btnExit.setBackground(new java.awt.Color(236, 242, 247));
        btnExit.setForeground(new java.awt.Color(72, 105, 149));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 102, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 158, -1));

        jLabel10.setBackground(new java.awt.Color(236, 242, 247));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 242, 247));
        jLabel10.setText("Boooking Id:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 158, -1));

        jLabel2.setBackground(new java.awt.Color(236, 242, 247));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 242, 247));
        jLabel2.setText("Customer Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        Search.setBackground(new java.awt.Color(236, 242, 247));
        Search.setForeground(new java.awt.Color(72, 105, 149));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jLabel3.setBackground(new java.awt.Color(236, 242, 247));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 242, 247));
        jLabel3.setText("IC/Passpord Number:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        cmbInDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmbInDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbInDayActionPerformed(evt);
            }
        });
        jPanel1.add(cmbInDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 50, -1));

        cmbInMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbInMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbInMonthActionPerformed(evt);
            }
        });
        jPanel1.add(cmbInMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 50, -1));

        cmbInYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027" }));
        cmbInYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbInYearActionPerformed(evt);
            }
        });
        jPanel1.add(cmbInYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 70, -1));

        jLabel7.setBackground(new java.awt.Color(236, 242, 247));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 242, 247));
        jLabel7.setText("Check-in Date:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel6.setBackground(new java.awt.Color(236, 242, 247));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 242, 247));
        jLabel6.setText("Room Id:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 60, -1));

        cmbRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210" }));
        cmbRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoomActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 93, -1));

        btnSearchRoom.setBackground(new java.awt.Color(236, 242, 247));
        btnSearchRoom.setForeground(new java.awt.Color(72, 105, 149));
        btnSearchRoom.setText("Search Room");
        btnSearchRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchRoomActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));
        jPanel1.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 90, -1));

        btnCal.setBackground(new java.awt.Color(236, 242, 247));
        btnCal.setForeground(new java.awt.Color(72, 105, 149));
        btnCal.setText("Calculate");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });
        jPanel1.add(btnCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 98, -1));

        jLabel9.setBackground(new java.awt.Color(236, 242, 247));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 242, 247));
        jLabel9.setText("Amount:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        jLabel5.setBackground(new java.awt.Color(236, 242, 247));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 242, 247));
        jLabel5.setText("Email:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 580, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoomActionPerformed
       
    }//GEN-LAST:event_cmbRoomActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtName.setText("");
        txtIcNo.setText("");
        txtPhoneNo.setText("");
        txtEmail.setText("");
        
        cmbRoom.setSelectedIndex(0);
        txtAmount.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String id,name,phone, ic,email, amount, inDate,outDate,roomId;
        int newNum, highestNumber=0;   
        int numDays= (int)getNumDays();
        ArrayList<String> tempArray = new ArrayList<>();
        
        

        //get input from the form
        
        id=txtId.getText();
        name=txtName.getText();
        phone=txtPhoneNo.getText();
        ic=txtIcNo.getText();
        email=txtEmail.getText();
        inDate = getInDate();
        outDate = getOutDate();
        roomId=String.valueOf(cmbRoom.getSelectedItem());
        amount=txtAmount.getText();
        
        //validation
        Validation val = new Validation(name,ic,phone,email,inDate,outDate,amount);
        try{
            boolean isValid = val.formValidation();
            if(isValid){
                // update room to new date to not available
                RoomSettings obj2 = new RoomSettings(getInDate(), getOutDate(), numDays, roomId);
                obj2.updateRoomAvailability();
                 try{
                     //update old date for the room to available
                    
                    try(FileReader fr = new FileReader("bookingDetails.txt")){
                        Scanner reader = new Scanner(fr);
                        String line;
                        String[] lineArr;

                        while((line=reader.nextLine())!=null){
                            //split each line to check if the search id is present
                            lineArr = line.split(",");
                            if (lineArr[0].equals(id)){

                                //if the search id is present, add theold data
                                //plus the new data in to the temp array
                                tempArray.add(
                                id+","+
                                name+","+
                                ic+","+
                                phone+","+
                                email+","+
                                inDate+","+
                                outDate+","+
                                roomId+","+
                                amount
                                );
                                JOptionPane.showMessageDialog(null,"Updated completed.","Success",JOptionPane.INFORMATION_MESSAGE);
                            }else{

                                //if the search id doesnt match add the line as it is
                                tempArray.add(line);
                                
                            }
                        }
                        
                        fr.close();
                    }catch(Exception e){         
                    }

                }catch(Exception e){  
                }

                try{
                    // open teh print writer to write the data in temp array back to the file
                    try (java.io.PrintWriter pr = new java.io.PrintWriter("bookingDetails.txt")){
                        for(String str :tempArray){
                            //write all teh data in the temp array bak to the file line by line
                            pr.println(str);
                        }
                        pr.close();
                    }catch(Exception e){
                    }
                }catch(Exception e){

                }
            }else{
               
            }
        }catch (ParseException e){
            
        }
        
        //temporary array to hold the data that is read from file
        
        
       
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        txtName.setText("");
        txtIcNo.setText("");
        txtPhoneNo.setText("");
        txtEmail.setText("");
        
        cmbRoom.setSelectedIndex(0);
        txtAmount.setText("");
        
        ArrayList<String> tempArray = new ArrayList<>();
        //get id from the form
        
        String id=txtId.getText();
        
        //temporary array to hold the data that is read from file
        
        
        try{
            try(FileReader fr = new FileReader("bookingDetails.txt")){
                Scanner reader = new Scanner(fr);
                String line;
                String[] lineArr;
                
                while((line=reader.nextLine())!=null){
                    //split each line to check if the search id is present
                    lineArr = line.split(",");
                    if (lineArr[0].equals(id)){
                        txtName.setText(lineArr[1]);
                        txtIcNo.setText(lineArr[2]);
                        txtPhoneNo.setText(lineArr[3]);
                        txtEmail.setText(lineArr[4]);
                        inDate =lineArr[5];
                        int[] inDateParts = splitDate(inDate);
                        cmbInDay.setSelectedItem(inDateParts[0]);
                        cmbInMonth.setSelectedItem(String.valueOf(inDateParts[1]));
                        cmbInMonth.setSelectedItem(String.valueOf(inDateParts[2]));
                        
                        outDate =lineArr[6];
                        int[] outDateParts = splitDate(outDate);
                        cmbOutDay.setSelectedItem(outDateParts[0]);
                        cmbOutMonth.setSelectedItem(String.valueOf(outDateParts[1]));
                        cmbOutMonth.setSelectedItem(String.valueOf(outDateParts[2]));
                        
                        txtName.setText(lineArr[1]);
                        txtName.setText(lineArr[1]);
                        cmbRoom.setSelectedItem(lineArr[7]);
                        txtAmount.setText(lineArr[8]);
                        //if the search id is present, add theold data
                        //plus the new data in to the temp array
                        
                        
                    }else{
                        
                         
                        tempArray.add(line);
                    }
                }
                fr.close();
            }catch(Exception e){         
            }
            
        }catch(Exception e){  
        }
        String textFieldValue = txtName.getText();
        if (textFieldValue.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No such ID exist","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            
        }

    }//GEN-LAST:event_SearchActionPerformed

    private void btnSearchRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchRoomActionPerformed
        int numDays = (int)getNumDays()+1;

        cmbRoom.removeAllItems();
        RoomSettings obj1=new RoomSettings(numDays,getInDate(),getOutDate());
        String[] availableRooms = obj1.getAvailableRooms();
        for (int i = 0; i < availableRooms.length; i++) {
            if (availableRooms[i]!=null){
                cmbRoom.addItem(availableRooms[i]);
            }
        }
    }//GEN-LAST:event_btnSearchRoomActionPerformed

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        txtAmount.setText(String.valueOf(getTotal()));

    }//GEN-LAST:event_btnCalActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void cmbInMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInMonthActionPerformed
        Calendar calendar = Calendar.getInstance();
        int day = calendar.get(Calendar.DAY_OF_MONTH);
        int inMonth = Integer.parseInt(cmbInMonth.getSelectedItem().toString());
        int inYear = Integer.parseInt(cmbInYear.getSelectedItem().toString());
        int daysInMonth;

        try{
            switch(inMonth){
                case 2:

                if((inYear%4==0 )){
                    daysInMonth=29;
                    break;
                }else{
                    daysInMonth=28;
                    break;
                }
                case 4:
                case 6:
                case 9:
                case 11:
                daysInMonth=30;
                break;
                default:
                daysInMonth=31;
                break;
            }

            cmbInDay.removeAllItems();
            for(int i=1;i<=daysInMonth;i++){
                cmbInDay.addItem(String.valueOf(i));
            }
            cmbInDay.setSelectedItem(String.valueOf(day));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_cmbInMonthActionPerformed

    private void cmbInYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInYearActionPerformed

    }//GEN-LAST:event_cmbInYearActionPerformed

    private void cmbOutDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOutDayActionPerformed

    }//GEN-LAST:event_cmbOutDayActionPerformed

    private void cmbOutMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOutMonthActionPerformed
        Calendar calendar = Calendar.getInstance();
        int day = calendar.get(Calendar.DAY_OF_MONTH);
        int outMonth = Integer.parseInt(cmbOutMonth.getSelectedItem().toString());
        int outYear = Integer.parseInt(cmbOutYear.getSelectedItem().toString());
        int daysInMonth;

        try{
            switch(outMonth){
                case 2:

                if((outYear%4==0 )){
                    daysInMonth=29;
                    break;
                }else{
                    daysInMonth=28;
                    break;
                }
                case 4:
                case 6:
                case 9:
                case 11:
                daysInMonth=30;
                break;
                default:
                daysInMonth=31;
                break;
            }

            cmbOutDay.removeAllItems();
            for(int i=1;i<=daysInMonth;i++){
                cmbOutDay.addItem(String.valueOf(i));
            }
            cmbOutDay.setSelectedItem(String.valueOf(day+1));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_cmbOutMonthActionPerformed

    private void cmbOutYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOutYearActionPerformed

    }//GEN-LAST:event_cmbOutYearActionPerformed

    private void cmbInDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInDayActionPerformed

    }//GEN-LAST:event_cmbInDayActionPerformed
    
    
    
 
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearchRoom;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbInDay;
    private javax.swing.JComboBox<String> cmbInMonth;
    private javax.swing.JComboBox<String> cmbInYear;
    private javax.swing.JComboBox<String> cmbOutDay;
    private javax.swing.JComboBox<String> cmbOutMonth;
    private javax.swing.JComboBox<String> cmbOutYear;
    private javax.swing.JComboBox<String> cmbRoom;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIcNo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNo;
    // End of variables declaration//GEN-END:variables
}
